name: go
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: sudo ./build.bash setup
      - run: sudo ./build.bash build
      - run: sudo -E ./build.bash release
        env:
          GITHUB_TOKEN: ${{ secrets.GOTIP_TOKEN }}
