name: python
on: [push]
jobs:
  manylinux_x86_64:
    name: manylinux_x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: sudo ./build.bash setup
      - run: sudo ./build.bash wheel
      - run: sudo -E ./build.bash release
        env:
          GITHUB_TOKEN: ${{ secrets.GOTIP_TOKEN }}
  manylinux_aarch64:
    name: manylinux_aarch64
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v1
      - run: sudo ./build.bash setup
      - run: sudo ./build.bash wheel
      - run: sudo -E ./build.bash release
        env:
          GITHUB_TOKEN: ${{ secrets.GOTIP_TOKEN }}
  # musllinux_x86_64:
  #   name: musllinux_x86_64
  #   runs-on: ubuntu-latest
  #   container:
  #     image: phuslu/seashell:latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - run: bash ./build.bash setup
  #     - run: bash ./build.bash wheel
  #     - run: bash ./build.bash release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GOTIP_TOKEN }}
